[build]
  # Publish from the root directory since we're serving static files
  publish = "."
  # No build needed
  command = ":"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
